2016/09/01 01:33:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "main".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('main')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('main')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/main')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facil/index.php?r=site/main
---
2016/09/05 16:09:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:10:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:11:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:11:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:11:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:11:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:30:16 [error] [php] include(CAtiveRecord.php): failed to open stream: No such file or directory (/Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php:432)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): spl_autoload_call()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 16:30:22 [error] [php] include(CAtiveRecord.php): failed to open stream: No such file or directory (/Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php:432)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): spl_autoload_call()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 16:35:53 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:56 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:57 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:57 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:58 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:58 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:58 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:43:59 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:30 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:31 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:31 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:31 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:31 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:31 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:32 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:32 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:32 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:32 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:32 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:33 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:33 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:34 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:34 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:34 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 16:58:34 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:43 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:43 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:45 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:45 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:46 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:46 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:46 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:46 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:02:46 [error] [system.db.CDbCommand] Error in preparing SQL: PRAGMA table_info('schemas'.'usuario')
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario').
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:02:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 near ".": syntax error. The SQL statement executed was: PRAGMA table_info('schemas'.'usuario')' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(134): CDbCommand->queryAll()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/sqlite/CSqliteSchema.php(117): CSqliteSchema->findColumns(Object(CDbTableSchema))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/schema/CDbSchema.php(103): CSqliteSchema->loadTable('schemas.usuario')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(2386): CDbSchema->getTable('schemas.usuario')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:03:08 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:09 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:10 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:10 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:11 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:11 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:11 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:11 [error] [php] Use of undefined constant schemas - assumed 'schemas' (/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php:9)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): Users->getMetaData()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): Users->getTableSchema()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): Users->query()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): Users->findAll()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): HolaController->runAction()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): HolaController->runActionWithFilters()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): HolaController->run()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facil/hola/index
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/models/Users.php (9)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php (7)
in /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php (13)
2016/09/05 17:03:36 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:03:37 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:03:37 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:03:37 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:03:38 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:03:38 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:18:42 [error] [exception.CDbException] exception 'CDbException' with message 'The table "schemasusuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:05 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:06 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:06 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:06 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:06 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:07 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:07 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:07 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:07 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:19:07 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:01 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:02 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:02 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:02 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:03 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:04 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:04 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/05 17:20:05 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:21:28 [error] [exception.CDbException] exception 'CDbException' with message 'The table "usuario" for active record class "Users" cannot be found in the database.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php:2387
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/ar/CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(8): CActiveRecord->findAll()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:33:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:33:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:40:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] missing "=" after "/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/config/../data/testdrive.db" in connection info string' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:40:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] missing "=" after "/Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/config/../data/testdrive.db" in connection info string' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:07 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:08 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:08 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:09 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:09 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:09 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
2016/09/06 19:41:09 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.db" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:173
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(220): CComponent->__set('db', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/protected/controllers/HolaController.php(7): CModule->__get('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): HolaController->actionIndex()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('hola/index')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/facil/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/facil/hola/index
---
